# Generated by Django 4.2.5 on 2024-01-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
