# Generated by Django 4.2.5 on 2024-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_model',
            fields=[
                ('employee_name', models.CharField(max_length=20)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
